apiVersion: v1
kind: Service
metadata:
  labels:
    run: flaskhelloworld
  name: flaskhelloworld
  namespace: default
spec:
  ports:
  - nodePort: 31182
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: flaskhelloworld
  type: LoadBalancer

