apiVersion: v1
kind: Pod
metadata:
  labels:
    run: flaskhelloworld
  name: flaskhelloworld
  namespace: default
spec:
  containers:
  - name: flaskhelloworld
    image: barteks/flaskhelloworld:latest
    ports:
    - containerPort: 80
