language: python
python:
  - 3.6.8
services:
  - docker
before_install:
  - docker build --tag $DOCKER_USERNAME/flaskhelloworld .
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/flaskhelloworld
script:
  - python test/test_app.py
